<?php

// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Strings for component 'countries', language 'cs', branch 'MOODLE_23_STABLE'
 *
 * @package   countries
 * @copyright 1999 onwards Martin Dougiamas  {@link http://moodle.com}
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['AD'] = 'Andorra';
$string['AE'] = 'Spojené arabské emiráty';
$string['AF'] = 'Afghánistán';
$string['AG'] = 'Antigua a Barbuda';
$string['AI'] = 'Anguilla';
$string['AL'] = 'Albánie';
$string['AM'] = 'Arménie';
$string['AN'] = 'Nizozemské Antily';
$string['AO'] = 'Angola';
$string['AQ'] = 'Antarktida';
$string['AR'] = 'Argentina';
$string['AS'] = 'Americká Samoa';
$string['AT'] = 'Rakousko';
$string['AU'] = 'Austrálie';
$string['AW'] = 'Aruba';
$string['AX'] = 'Ålandy';
$string['AZ'] = 'Ázerbájdžán';
$string['BA'] = 'Bosna a Hercegovina';
$string['BB'] = 'Barbados';
$string['BD'] = 'Bangladéš';
$string['BE'] = 'Belgie';
$string['BF'] = 'Burkina Faso';
$string['BG'] = 'Bulharsko';
$string['BH'] = 'Bahrajn';
$string['BI'] = 'Burundi';
$string['BJ'] = 'Benin';
$string['BL'] = 'Svatý Bartoloměj';
$string['BM'] = 'Bermudy';
$string['BN'] = 'Brunej';
$string['BO'] = 'Bolívie';
$string['BR'] = 'Brazílie';
$string['BS'] = 'Bahamy';
$string['BT'] = 'Bhútán';
$string['BV'] = 'Bouvetův ostrov';
$string['BW'] = 'Botswana';
$string['BY'] = 'Bělorusko';
$string['BZ'] = 'Belize';
$string['CA'] = 'Kanada';
$string['CC'] = 'Kokosové ostrovy';
$string['CD'] = 'Demokratická republika Kongo';
$string['CF'] = 'Středoafrická republika';
$string['CG'] = 'Kongo';
$string['CH'] = 'Švýcarsko';
$string['CI'] = 'Pobřeží slonoviny';
$string['CK'] = 'Cookovy ostrovy';
$string['CL'] = 'Chile';
$string['CM'] = 'Kamerun';
$string['CN'] = 'Čína';
$string['CO'] = 'Kolumbie';
$string['CR'] = 'Kostarika';
$string['CU'] = 'Kuba';
$string['CV'] = 'Kapverdy';
$string['CX'] = 'Vánoční ostrov';
$string['CY'] = 'Kypr';
$string['CZ'] = 'Česká republika';
$string['DE'] = 'Německo';
$string['DJ'] = 'Džibutsko';
$string['DK'] = 'Dánsko';
$string['DM'] = 'Dominika';
$string['DO'] = 'Dominikánská republika';
$string['DZ'] = 'Alžírsko';
$string['EC'] = 'Ekvádor';
$string['EE'] = 'Estonsko';
$string['EG'] = 'Egypt';
$string['EH'] = 'Západní Sahara';
$string['ER'] = 'Eritrea';
$string['ES'] = 'Španělsko';
$string['ET'] = 'Etiopie';
$string['FI'] = 'Finsko';
$string['FJ'] = 'Fidži';
$string['FK'] = 'Falklandy (Malvíny)';
$string['FM'] = 'Mikronésie';
$string['FO'] = 'Faerské ostrovy';
$string['FR'] = 'Francie';
$string['GA'] = 'Gabun';
$string['GB'] = 'Velká Británie';
$string['GD'] = 'Grenada';
$string['GE'] = 'Georgia';
$string['GF'] = 'Francouzská Guyana';
$string['GG'] = 'Guernsey';
$string['GH'] = 'Ghana';
$string['GI'] = 'Gibraltar';
$string['GL'] = 'Grónsko';
$string['GM'] = 'Gambie';
$string['GN'] = 'Guinea';
$string['GP'] = 'Guadeloupe';
$string['GQ'] = 'Rovníková Guinea';
$string['GR'] = 'Řecko';
$string['GS'] = 'Jižní Georgie a Jižní Sandwichovy ostrovy';
$string['GT'] = 'Guatemala';
$string['GU'] = 'Guam';
$string['GW'] = 'Guinea-Bissau';
$string['GY'] = 'Guyana';
$string['HK'] = 'Hongkong';
$string['HM'] = 'Heardův ostrov a McDonaldovy ostrovy';
$string['HN'] = 'Honduras';
$string['HR'] = 'Chorvatsko';
$string['HT'] = 'Haiti';
$string['HU'] = 'Maďarsko';
$string['ID'] = 'Indonésie';
$string['IE'] = 'Irsko';
$string['IL'] = 'Izrael';
$string['IM'] = 'Ostrov Man';
$string['IN'] = 'Indie';
$string['IO'] = 'Britské indickooceánské území';
$string['IQ'] = 'Irák';
$string['IR'] = 'Írán';
$string['IS'] = 'Island';
$string['IT'] = 'Itálie';
$string['JE'] = 'Jersey';
$string['JM'] = 'Jamajka';
$string['JO'] = 'Jordánsko';
$string['JP'] = 'Japonsko';
$string['KE'] = 'Keňa';
$string['KG'] = 'Kyrgyzstán';
$string['KH'] = 'Kambodža';
$string['KI'] = 'Kiribati';
$string['KM'] = 'Komory';
$string['KN'] = 'Svatý Kryštof a Nevis';
$string['KP'] = 'Korejská lidově demokratická republika';
$string['KR'] = 'Korea';
$string['KW'] = 'Kuvajt';
$string['KY'] = 'Kajmanské ostrovy';
$string['KZ'] = 'Kazachstán';
$string['LA'] = 'Laos';
$string['LB'] = 'Libanon';
$string['LC'] = 'Svatá Lucie';
$string['LI'] = 'Lichtenštejnsko';
$string['LK'] = 'Srí Lanka';
$string['LR'] = 'Libérie';
$string['LS'] = 'Lesotho';
$string['LT'] = 'Litva';
$string['LU'] = 'Lucembursko';
$string['LV'] = 'Lotyšsko';
$string['LY'] = 'Libye';
$string['MA'] = 'Maroko';
$string['MC'] = 'Monako';
$string['MD'] = 'Moldávie';
$string['ME'] = 'Černá Hora';
$string['MF'] = 'Svatý Martin';
$string['MG'] = 'Madagaskar';
$string['MH'] = 'Marshallovy ostrovy';
$string['MK'] = 'Makedonie';
$string['ML'] = 'Mali';
$string['MM'] = 'Myanmar';
$string['MN'] = 'Mongolsko';
$string['MO'] = 'Macao';
$string['MP'] = 'Severní Mariany';
$string['MQ'] = 'Martinik';
$string['MR'] = 'Mauritánie';
$string['MS'] = 'Montserrat';
$string['MT'] = 'Malta';
$string['MU'] = 'Mauricius';
$string['MV'] = 'Maledivy';
$string['MW'] = 'Malawi';
$string['MX'] = 'Mexiko';
$string['MY'] = 'Malajsie';
$string['MZ'] = 'Mosambik';
$string['NA'] = 'Namibie';
$string['NC'] = 'Nová Kaledonie';
$string['NE'] = 'Niger';
$string['NF'] = 'Norfolk';
$string['NG'] = 'Nigérie';
$string['NI'] = 'Nikaragua';
$string['NL'] = 'Nizozemsko';
$string['NO'] = 'Norsko';
$string['NP'] = 'Nepál';
$string['NR'] = 'Nauru';
$string['NU'] = 'Niue';
$string['NZ'] = 'Nový Zéland';
$string['OM'] = 'Omán';
$string['PA'] = 'Panama';
$string['PE'] = 'Peru';
$string['PF'] = 'Francouzská Polynésie';
$string['PG'] = 'Papua-Nová Guinea';
$string['PH'] = 'Filipíny';
$string['PK'] = 'Pákistán';
$string['PL'] = 'Polsko';
$string['PM'] = 'Saint-Pierre a Miquelon';
$string['PN'] = 'Pitcairn';
$string['PR'] = 'Portoriko';
$string['PS'] = 'Palestina';
$string['PT'] = 'Portugalsko';
$string['PW'] = 'Palau';
$string['PY'] = 'Paraguay';
$string['QA'] = 'Katar';
$string['RE'] = 'Réunion';
$string['RO'] = 'Rumunsko';
$string['RS'] = 'Srbsko';
$string['RU'] = 'Ruská federace';
$string['RW'] = 'Rwanda';
$string['SA'] = 'Saúdská Arábie';
$string['SB'] = 'Šalamounovy ostrovy';
$string['SC'] = 'Seychely';
$string['SD'] = 'Súdán';
$string['SE'] = 'Švédsko';
$string['SG'] = 'Singapur';
$string['SH'] = 'Svatá Helena';
$string['SI'] = 'Slovinsko';
$string['SJ'] = 'Špicberky';
$string['SK'] = 'Slovenská republika';
$string['SL'] = 'Sierra Leone';
$string['SM'] = 'San Marino';
$string['SN'] = 'Senegal';
$string['SO'] = 'Somálsko';
$string['SR'] = 'Surinam';
$string['ST'] = 'Svatý Tomáš a Princův ostrov';
$string['SV'] = 'Salvador';
$string['SY'] = 'Sýrie';
$string['SZ'] = 'Svazijsko';
$string['TC'] = 'Turks a Caicos';
$string['TD'] = 'Čad';
$string['TF'] = 'Francouzská jižní území';
$string['TG'] = 'Togo';
$string['TH'] = 'Thajsko';
$string['TJ'] = 'Tádžikistán';
$string['TK'] = 'Tokelau';
$string['TL'] = 'Východní Timor';
$string['TM'] = 'Turkmenistán';
$string['TN'] = 'Tunisko';
$string['TO'] = 'Tonga';
$string['TR'] = 'Turecko';
$string['TT'] = 'Trinidad a Tobago';
$string['TV'] = 'Tuvalu';
$string['TW'] = 'Tchaj-wan';
$string['TZ'] = 'Tanzanie';
$string['UA'] = 'Ukrajina';
$string['UG'] = 'Uganda';
$string['UM'] = 'Menší odlehlé ostrovy USA';
$string['US'] = 'Spojené státy americké';
$string['UY'] = 'Uruguay';
$string['UZ'] = 'Uzbekistán';
$string['VA'] = 'Vatikán';
$string['VC'] = 'Svatý Vincenc a Grenadiny';
$string['VE'] = 'Venezuela';
$string['VG'] = 'Panenské ostrovy (Velká Británie)';
$string['VI'] = 'Panenské ostrovy (USA)';
$string['VN'] = 'Vietnam';
$string['VU'] = 'Vanuatu';
$string['WF'] = 'Wallisovy ostrovy';
$string['WS'] = 'Samoa';
$string['YE'] = 'Jemen';
$string['YT'] = 'Mayotte';
$string['ZA'] = 'Jižní Afrika';
$string['ZM'] = 'Zambie';
$string['ZW'] = 'Zimbabwe';
